# Generated by Django 4.2.24 on 2025-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field_3',
        ),
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.SlugField(default='Test value.'),
        ),
    ]
